import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/layouts/Header";
import ArsFooter from "./components/layouts/ArsFooter";
import { CartProvider } from "./contexts/CartContext"; // Adjust path as needed
import MainFooter from "./components/layouts/MainFooter";
import SEOFooter from "./components/layouts/SEOFooter";
import PayDelFooter from "./components/layouts/PayDelFooter";
import { AuthProvider } from "./contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CartProvider>
            <Header />
            {children}
            <MainFooter />
            <PayDelFooter />
            <SEOFooter />
            <ArsFooter />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
